server:
  port: 8082

spring:
thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8
  content-type: text/html
  mode: HTML5

druid:
 jdbc:
   driveClassName: com.mysql.jdbc.Driver
   jdbcUrl: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf8
   jdbcUsername: root
   jdbcPassword: woshiliyu921102
   maxActive: 20
   initialSize: 1
   maxWait: 60000
   minIdle: 3
   timeBetweenEvictionRunsMillis: 60000
   minEvictableIdleTimeMillis: 300000
   validationQuery: SELECT 'x'
   testWhileIdle: true
   testOnBrowwon: false
   testOnReturn: false
   filters: stat,wall

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.ly.generator.entity